version: '3.9'
services:
  webapp:
    environment:
      - TAG1=$TAG
    image: registry.digitalocean.com/ci-cd-playground-registry/ci-cd-playground-web:$TAG1
    restart: always
    networks:
      - ci-cd-playground-network
    ports:
      - "80:80"
networks:
  ci-cd-playground-network: