version: '3.9'
services:
  webapp:
    image: registry.digitalocean.com/ci-cd-playground-registry/ci-cd-playground-web:$TAG
    restart: always
    networks:
      - ci-cd-playground-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/certs/ci-cd-playground.ddns.net:/app/certs
networks:
  ci-cd-playground-network: